"""flagg.

Revision ID: 48b47ab64c60
Revises: d7e4f3fb4c92
Create Date: 2024-01-11 01:22:59.868631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48b47ab64c60'
down_revision = 'd7e4f3fb4c92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('available', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('available')

    # ### end Alembic commands ###
